pipeline {

    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('Lakshmi')
        AWS_SECRET_ACCESS_KEY = credentials('Lakshmi')
        AWS_DEFAULT_REGION    = 'us-east-1'
        PATH                  = "/usr/local/bin:${env.PATH}"
    }

    stages {

        stage('Checkout') {
            steps {
                echo '========== Pulling Code from Git =========='
                checkout scm
            }
        }

        stage('Terraform Version') {
            steps {
                echo '========== Checking Terraform Version =========='
                sh '/usr/local/bin/terraform version'
            }
        }

        stage('Terraform Init') {
            steps {
                echo '========== Initializing Terraform =========='
                dir('terraform-aws-infra') {
                    sh '/usr/local/bin/terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                echo '========== Validating Terraform Code =========='
                dir('terraform-aws-infra') {
                    sh '/usr/local/bin/terraform validate'
                }
            }
        }

        stage('Terraform Format Check') {
            steps {
                echo '========== Checking Terraform Formatting =========='
                dir('terraform-aws-infra') {
                    sh '/usr/local/bin/terraform fmt -check -recursive'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                echo '========== Planning Terraform Changes =========='
                dir('terraform-aws-infra') {
                    sh '/usr/local/bin/terraform plan -var-file="terraform.tfvars" -out=tfplan'
                }
            }
        }

        stage('Approval') {
            steps {
                echo '========== Waiting for Manual Approval =========='
                timeout(time: 5, unit: 'MINUTES') {
                    input message: '''Review the plan:
                    - 1 VPC (10.0.0.0/16)
                    - 2 Public Subnets
                    - 2 Private Subnets
                    - 1 EC2 Instance (t3.micro)
                    Do you want to Apply?''',
                    ok: 'Yes, Apply!'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                echo '========== Applying Terraform Changes =========='
                dir('terraform-aws-infra') {
                    sh '/usr/local/bin/terraform apply -auto-approve tfplan'
                }
            }
        }

        stage('Show Outputs') {
            steps {
                echo '========== Terraform Outputs =========='
                dir('terraform-aws-infra') {
                    sh '/usr/local/bin/terraform output'
                }
            }
        }

    }

    post {

        success {
            echo '''
            ========== SUCCESS ==========
            Resources Created:
            - VPC             : my-vpc
            - Public Subnets  : 2 (us-east-1a, us-east-1b)
            - Private Subnets : 2 (us-east-1a, us-east-1b)
            - EC2 Instance    : my-ec2-instance (t3.micro)
            ==============================
            '''
        }

        failure {
            echo '''
            ========== FAILED ==========
            Possible reasons:
            - Terraform not installed
            - Wrong AWS credentials
            - Invalid ami_id in terraform.tfvars
            - Wrong key_name in terraform.tfvars
            ==============================
            '''
        }

        always {
            echo '========== Pipeline Finished =========='
            cleanWs()
        }

    }

}